version: '3'

services:

  postgres:
    image: 'postgres:15'
    ports:
      - "5436:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: autoimport